### ISSUE TITLE
.NET Agent linux install package name/install path changing in agent version 10.0+

### ISSUE THREAD

**Issue by nr-ahemsath** [newrelic/newrelic-diagnostics-cli#114]
## Summary

With .NET agent version 10.0.0 and above, the names of the install packages for Linux are changing from `newrelic-netcore20-agent` to `newrelic-dotnet-agent`.  The install path on disk is also changing from `/usr/local/newrelic-netcore20-agent` to `/usr/local/newrelic-dotnet-agent`.  NrDiag needs to be updated to handle the new package name and install location.

## Desired Behavior

Ideally, NrDiag can be made to handle both cases, since we will need to continue supporting older versions in the field for as long as New Relic's support policy for agents requires that we do so.

## Possible Solution

It looks like these are the places in the NrDiag codebase where the `newrelic-netcore20-agent` string appears:

https://github.com/newrelic/newrelic-diagnostics-cli/blob/b963c5262c5ec7a79c4386948cc0c7509f2f6702/tasks/base/config/collect.go#L150
https://github.com/newrelic/newrelic-diagnostics-cli/blob/b963c5262c5ec7a79c4386948cc0c7509f2f6702/tasks/base/log/logHelpers.go#L138
https://github.com/newrelic/newrelic-diagnostics-cli/blob/b963c5262c5ec7a79c4386948cc0c7509f2f6702/tasks/dotnetcore/agent/installed.go#L16

Beyond that I'm not familiar enough with how NrDiag works to suggest how to solve this.  I can be available to help work on the solution/test possible solutions if necessary.

**Comment by daffinito** [comment]
Hi @nr-ahemsath thanks for keeping us up to date on the new dotnet agent changes! We'll get a ticket added to the backlog for this.
