### ISSUE TITLE
Python 3.9.15 not supported even though 3.9 is supported

### ISSUE THREAD

**Issue by glevine** [newrelic/newrelic-diagnostics-cli#159]
## Description

I am not seeing all traces that I expect in a Python application. I ran the diagnostics tool to see why. The only error that I see is

> Failure - Python/Requirements/PythonVersion
Your 3.9.15 Python version is not in the list of supported versions by the Python Agent. Please review our documentation on version requirements
See https://docs.newrelic.com/docs/agents/python-agent/getting-started/compatibility-requirements-python-agent#basic for more information.

There are no problems with tracing Celery tasks in the same environment with the same Python version.

## Steps to Reproduce

* Create a Python virtual environment with Python 3.9.15
* Install and configure the New Relic Python Agent 8.7.0
* Install nrdiag
* Run `./nrdiag -a -s python -c /etc/newrelic.ini -output-path /tmp/nrdiag -v`

## Expected Behavior

https://docs.newrelic.com/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent/#basic says:

> Python (CPython/PyPy) versions supported: 2.7, 3.7, 3.8, 3.9, 3.10, and 3.11.
> Recommendation: Use Python version 3.7 or higher with our agent.

I expect 3.9.15 to be supported.

## Relevant Logs / Console output

The output says that 3.9.15 is not supported.

> Failure - Python/Requirements/PythonVersion
Your 3.9.15 Python version is not in the list of supported versions by the Python Agent.

## Your Environment

* `uname -m`: `x86_64`
* Kubernetes v1.25.6
* Python 3.9.15
* Django 3.2.18
* New Relic Python Agent 8.7.0
* New Relic Diagnostics - release version - 2.4.2 - Build timestamp - 2023-04-05_09:17:45PM

**Comment by daffinito** [comment]
Hi @glevine , thanks for reporting this! We'll get the task updated!
