### ISSUE TITLE
Something bad happened [that was literally the error message, LOL]

### ISSUE THREAD

**Issue by KaliforniaShell** [newrelic/newrelic-diagnostics-cli#218]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behavior

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( the agents where were stuck outside unable to return home and work starved of energy. Apparently it was the issue with onboarding them back into the server connecting to the app)
-![BUILD-TIME_ENVS.md](https://github.com/newrelic/newrelic-diagnostics-cli/files/14195844/BUILD-TIME_ENVS.md)

**Comment by daffinito** [comment]
Hi @KaliforniaShell, thanks for reporting this! Could you please provide some details on how to reproduce the error? 
* OS of the host where you ran nrdiag
* nrdiag command line options you used
* Were you using the latest version of nrdiag? (`nrdiag -version` to check)
* Was there any other output on the screen?

Thank you!

**Comment by daffinito** [comment]
Hi @KaliforniaShell! I'm going to go ahead and close this issue, however please don't hesitate to reopen it if you are able to reproduce this and can provide more details. Thank you.

**Comment by KaliforniaShell** [comment]
> Hi @KaliforniaShell! I'm going to go ahead and close this issue, however please don't hesitate to reopen it if you are able to reproduce this and can provide more details. Thank you.

Cheers, mate! Appreciate the help. Will do, bruv.
