### ISSUE TITLE
Hi @KaliforniaShell, thanks for reporting this! Could you please provide some details on how to reproduce the,...No I can't unfortunately 

### ISSUE THREAD

**Issue by KaliforniaShell** [newrelic/newrelic-diagnostics-cli#220]
Hi @KaliforniaShell, thanks for reporting this! Could you please provide some details on how to reproduce the error? 
* OS of the host where you ran nrdiag was kubernetes
* nrdiag command line options you used 'one of the 2 apps we had at the time?' not sure'
* Were you using the latest version of nrdiag? (`nrdiag -version` to check) 'not sure'
* Was there any other output on the screen? 'possibly'

Thank you!

_Originally posted by @daffinito in https://github.com/newrelic/newrelic-diagnostics-cli/issues/218#issuecomment-1939324809_

**Comment by daffinito** [comment]
hi @KaliforniaShell , thank for following up!
I'm sorry to ask more questions but I'm afraid I haven't been able to reproduce this yet, and hopefully these questions will help me narrow this down:

- Did you run the CLI on a k8s node or pod? (or other)?
- Kubernetes itself isn't an OS - what OS was the host specifically running?
- What product were you troubleshooting when you ran the cli? Infrastructure agent, APM agent, etc? If APM Agent - what language specifically?
- Are you able to reproduce this issue? Can you provide steps to reproduce it?

Thanks you!

**Comment by daffinito** [comment]
hi @KaliforniaShell , I'm going to go ahead and close this issue out for now. Please don't hesitate to reopen this if you run into any further issues or have any additional details to provide on this one. Thank you!
