### ISSUE TITLE
Revise how we collect logs for python agent

### ISSUE THREAD

**Issue by uturunku1** [newrelic/newrelic-diagnostics-cli#27]
## Description

Log collection for Python agent may be broken as config files take precedence over env vars.
Over here https://github.com/newrelic/newrelic-diagnostics-cli/blob/main/tasks/base/log/logHelpers.go#L117-L129 we are making the assumption that we should prioritize the location of agent logs by looking at the env vars values. That is because most agent env vars will overwrite whatever was configured in the config file. Except for the python agent.

**Comment by daffinito** [comment]
It looks like the code has changed for logHelpers and we do collect log files from config file settings also:

https://github.com/newrelic/newrelic-diagnostics-cli/blob/4cee13d0c18ad2a1773fbcfd0c677e535cb18828/tasks/base/log/logHelpers.go#L189-L194
