### ISSUE TITLE
Add a URL to Java/env/process

### ISSUE THREAD

**Issue by uturunku1** [newrelic/newrelic-diagnostics-cli#29]
## Summary

A lot of customers fail at passing the -javaagent flag in docker. It would be great to recommend this doc to fix their issue is this task fails for them: https://discuss.newrelic.com/t/relic-solution-what-you-need-to-know-about-new-relic-when-deploying-with-docker/52492

## Where to fix

https://github.com/newrelic/newrelic-diagnostics-cli/blob/main/tasks/java/env/process.go#L98-L100

**Comment by daffinito** [comment]
Looks like we're good to go:

https://github.com/newrelic/newrelic-diagnostics-cli/blob/main/tasks/java/env/process.go#L120
