### ISSUE TITLE
 NewRelic upgrade to 5.9.0 from 3.0 is not working. UI wont see any data coming through after upgrade. All dir structure with newrelic.yml and .jar files are in right dir. 

### ISSUE THREAD

**Issue by jeshwanth-harish** [newrelic/newrelic-diagnostics-cli#76]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behavior

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by daffinito** [comment]
Hi @jeshwanth-harish, my apologies for the delay in responding to this. It sounds like you ran into issues after upgrading the java agent to version 5.9.0. I recommend reaching out to support. You can find your options for support by clicking on the "I need more help" button here: https://one.newrelic.com/nr1-core/help-xp/home
