### ISSUE TITLE
Installation instructions for Docker are missing

### ISSUE THREAD

**Issue by chadsaun** [newrelic/newrelic-diagnostics-cli#78]
The README.md says under "Installation" that "To install in a Docker container see [here](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics#h2-run-new-relic-diagnostics-in-a-docker-container)". This link doesn't take you to any instructions specific to Docker.

Are they any instructions out there for installing with Docker?

**Comment by GabrielSamp** [comment]
Hi @chadsaun Thanks for raising this. It looks like we were using an old URL. I updated the readme and this should be resolved.
