### ISSUE TITLE
Installation instructions incomplete / misleading

### ISSUE THREAD

**Issue by kassi** [newrelic/newrelic-diagnostics-cli#84]
## Description

Following the link provided on [No data appears (Infrastructure) page](https://docs.newrelic.com/docs/infrastructure/infrastructure-troubleshooting/troubleshoot-infrastructure/no-data-appears-infrastructure/) via [Diagnostics CLI page](ttps://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag/) I followed the instructions to install this tool given in the README, but there's nothing describing where the tool is or how to build it.

## Steps to Reproduce

As given in the README:
1. Download a zip of the latest version (I tried both, Code -> Download ZIP and Releases -> Source Code (ZIP))
2. Extract the zip, and select the executable file for your OS. -> No executable found, no according directory leading to the binary or system architecture with a tool inside.
3. Even a `find . -name 'nrdiag*'` doesn't provide any result.

## Expected Behavior

Either an executable on top level or in a bin directory or in a directory named by my os (linux).

## Your Environment

Linux (rasbperry buster) and Mac (Catalina)

**Comment by GabrielSamp** [comment]
Hi @kassi Thanks for raising this. I added a link in that section of the readme to directly download the latest version. I am going to close this now but let me know if you have any other questions.
