### ISSUE TITLE
ATemplateforNewRelic

### ISSUE THREAD

**Issue by ChristianityWebb** [newrelic/newrelic-diagnostics-cli#91]
NOTE
 Provide a general summary of the request in the title above. ^^ )

Summary

NOTE
Provide a brief overview of what the new feature is all about. )
Desired Behavior

NOTE
Tell us how the new feature should work. Be specific. )
TIP
Do NOT give us access or passwords to your New Relic account or API keys! )

Possible Solution

NOTE
Not required. Suggest how to implement the addition or change. )
Additional context
TIP
Why does this feature matter to you? What unique circumstances do you have? )

**Comment by daffinito** [comment]
Hi @ChristianityWebb! Thanks for reaching out! This looks like our current template so I'm going to go ahead and close this out. Please don't hesitate to reopen it if I'm mistaken or if there's anything else we can help with.
